# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'AirportLookUp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for AirportLookUp
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod "BWWalkthrough"
  pod 'Mapbox-iOS-SDK'

  target 'AirportLookUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AirportLookUpUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
